### PR TITLE
Added Star button

### PR DESCRIPTION
**Pull request by Anuran12**
Close: #26 

I added star button. You can merge it now  ^_^

Happy to contribute 😁

### CODE REVIEW

**Comment by heysagnik** [comment]
Well done will do a little fix before merging

**Comment by Anuran12** [comment]
What ?

**Comment by Anuran12** [comment]
? @heysagnik

**Comment by Anuran12** [comment]
@heysagnik hey...

**Comment by Anuran12** [comment]
what should i do ?

**Comment by heysagnik** [comment]
Actually I want to fix the ui of the star button as the 
https://codepen.io/aaroniker/pen/BaZJMjv

**Comment by Anuran12** [comment]
@heysagnik  Okay I will. But the thing is I am unable to access the button's styling in scss . could you help me ?

**Comment by heysagnik** [comment]
Actually I am away from keyboard ⌨️ , you have to wait for 2 more days so that I can help you. 
Till then you can work on any other projects. Becoz time is running out for Hacktoberfest.

**Comment by Anuran12** [comment]
@heysagnik  okay... Just tell me how I can access the styling of the button then i will change the style as you want. Actually i am using pug and scss for the first time.

**Comment by heysagnik** [comment]
I would make a simple button instead of 
[the one](https://buttons.github.io/) you used.and did a styling with scss.
[This may help you to understand the basic of pug .](https://bedrockapp.org/documentation/working-with-pug/) 
Likewise will use `<a>` and linked to the repo .
If you face difficulties with scss then create a seperate style.css to use css for the button.

**Comment by Anuran12** [comment]
Okay

**Comment by Anuran12** [comment]
@heysagnik  hey I changed the styling according to your reference but I am unable to make the star animation because the javascript giving me error.

**Comment by Anuran12** [comment]
@heysagnik Sorry I am unable to do this.. you better have to find someone else. I am unassigning  from this

**Comment by heysagnik** [comment]
Ok

**Comment by Anuran12** [comment]
@heysagnik hey can you merge it please ? then later you will modify the button. 🙂

**Pull request merged**
