### PR TITLE
Feat: save color scheme to local storage

### LINKED ISSUE #30: Save user selected color scheme to localstorage
**Is your feature request related to a problem? Please describe.**

Users have to select color scheme every time they visit the page, if they want to use a different color scheme from browser's default color scheme.

**Describe the solution you'd like**

- After user toggles color scheme, save their decision to localstorage.
  - key : `screenREC-color-scheme`
  - value : "light" | "dark"
- Before querying browser's `prefers-color-scheme` for color scheme, see if there is an existing color scheme in localstorage

**Describe alternatives you've considered**

Sorry, I could not think of any alternatives.

Does this feature request sounds appeal to you? if so, I'm willing to make a PR for this!

### PR DESCRIPTION
**Pull request by BWsix**
This PR fixes #30
Let me know if there's anything that needs to be changed!

### CODE REVIEW

**Comment by heysagnik** [comment]
Good Job 👍

**Comment by BWsix** [comment]
Thank you too!

**Comment by heysagnik** [comment]
Can you help me with any of these issues?
#21 #1

**Comment by BWsix** [comment]
@heysagnik 
Sure, I'll take a look into both of them!
I'll let you know if I do not know how to do fix them.

Oh and, I did managed to record for 20 minutes.

**Comment by heysagnik** [comment]
> 

👍

**Pull request merged**
