### PR TITLE
Fix: app crash after clicking `Stop Sharing` button

### LINKED ISSUE #1: Detect the user's device
If the user is  using mobile phone to access this site then don't allow the user to use this website and display an error message  else allow the user to use this website

### LINKED ISSUE #21: Stop sharing button bug
**Describe the bug**
App crashes if the user clicks on ``` Stop sharing ``` button.

image

**To Reproduce**
Steps to reproduce the behaviour:
1. Start recording
2. Click on ```Stop sharing``` button of the chrome popup UI.
3. App crashes here!

**Expected behaviour**
Recording should be stopped and video recorded till that time should be saved.

**Screenshots**
image

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 105.0.5195.127

### PR DESCRIPTION
**Pull request by BWsix**
This PR fixes #21, the app will no longer crash after user clicks `Stop Sharing` button.
Let me know if there anything that needs to be changed!

Also, I'm not sure if I can fix #1, since I'm not familiar with pug.
I'm still trying but I'll let you know if I decided to give up.

### CODE REVIEW

**Comment by BWsix** [comment]
Sorry, I will not do #1, it's too hard for me.

**Comment by heysagnik** [comment]
the issue isn't fixed :( 
The issue is that when you click `Stop Sharing button` , the recording should get stopped and vice versa.

**Comment by BWsix** [comment]
Oh I get it, I only solved half of the issue right?

**Comment by BWsix** [comment]
@heysagnik
I think it's now fully fixed!
- After clicking `Stop Sharing`, the record ends.
- After manually ending the record, the `Stop Sharing` button disappears.

**Comment by heysagnik** [comment]
thanks for the PR but it didn't worked :) 
Please don't delete the branch I am looking into the code ...
Is this PR regarding `hacktoberfest` ? Then I would add `hacktoberfest-accepted` label

**Comment by BWsix** [comment]
> thanks for the PR but it didn't worked :) Please don't delete the branch I am looking into the code ... Is this PR regarding `hacktoberfest` ? Then I would add `hacktoberfest-accepted` label

Yeah that would be great if you could add the label, thank in advance!
Oh I found that it does not work on google chrome. It works on firefox though🤔.
https://user-images.githubusercontent.com/57709309/194716969-3a26769f-a058-438c-aeb2-dcc7e9d285a1.mp4

**Comment by BWsix** [comment]
@heysagnik
Okay I think it is fixed now, as it will not crash on Chrome browser.

**Comment by heysagnik** [comment]
Great man 👨

**Pull request merged**
