### PR TITLE
chore: Updated README with typo fixes and usage instructions.

### PR DESCRIPTION
**Pull request by guiszk**
I also added the video example, hosted on Imgur.

### CODE REVIEW

**Review by heysagnik — CHANGES_REQUESTED** [review]
Sorry to ask ,can you create a new video showcasing the tutorial. Actually had to revert back to original UI due to security vulnerabilities

**Comment by guiszk** [comment]
Sure

**Comment by heysagnik** [comment]
> Sure

Check I have updated the readme file ,
Just delete this PR and create a new one

**Review by heysagnik — APPROVED** [review]

**Comment by heysagnik** [comment]
> > Sure
> 
> Check I have updated the readme file , Just delete this PR and create a new one

Okay but If I delete and create a new one then, you won't be there in contribution list / not applicable for hacktoberfest

**Comment by guiszk** [comment]
Won't my first commit show up as contribution?

**Pull request closed without merging**
