### PR TITLE
mic record feature

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
This Feature is a Part of #2 

**Please Note: Merge this request first then ask people to pull and then add their features. The mic feature is built on existing code base. Also please test out the feature :)**

Mic option have been separated 

If User doesnt give permission to mic :)

### CODE REVIEW

**Comment by Suraj-Bhandarkar-S** [comment]
#20 Web Cam Feature has also been integrated with Same pull request 

webcam-3
webcam-4
webcam-5
webcam-6
Webcam-1
webcam-2

**Comment by heysagnik** [comment]
good man :) which browser is that ? For chrome it isn't working

**Comment by heysagnik** [comment]
I think so much in a single dropdown menu is a boring one 
If we create the UI like [this](https://www.screencapture.com/) ?

**Comment by Suraj-Bhandarkar-S** [comment]
image
I tried in chrome its working for me, not sure we can connect on this whenever your free :)

**Comment by heysagnik** [comment]
I have added the Hacktoberfest label and tomorrow I will look into the code , GN

**Comment by Suraj-Bhandarkar-S** [comment]
Submitted A bug Fix for Mic not working in MP4 with mic and Webm with MIC, hopefully this fixes the issue of prod :)

**Comment by Suraj-Bhandarkar-S** [comment]
Let me know the error you are getting in chrome - 

My Chrome Version is : Version 106.0.5249.119 (Official Build) (64-bit) running on Windows 10 

Also can you try on other browsers and let me know if its the same issue. Thanks

**Comment by heysagnik** [comment]
Check nothing is working on my father's browser too
https://user-images.githubusercontent.com/70798495/195572624-c0252d37-18a7-4443-bf37-7266240c6df3.mp4

**Comment by Suraj-Bhandarkar-S** [comment]
okay there is some code merge issue happening, will have to review the code base i worked on had never had naming the video part

**Comment by Suraj-Bhandarkar-S** [comment]
also can you share what you are getting in console

**Comment by Suraj-Bhandarkar-S** [comment]
I will be creating a new pull request based on the existing code in the repo.

**Pull request closed without merging**
