### PR TITLE
Web Cam and Voice Recording Fix

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
Hopefully This fixes the issue in your system. Working for me in Chrome.

### CODE REVIEW

**Comment by Suraj-Bhandarkar-S** [comment]
#2 #20 2 issues are addressed in this pull request.  Attaching video and audio file.

**Warning: In below Recorded Video the audio quality is bit loud and bad. keep volume low.**

https://user-images.githubusercontent.com/42907076/195600167-bd85bcbb-442d-49b0-ba33-7336d441a11b.mp4

**Comment by heysagnik** [comment]
#2 yeah this solves the issue. 
Can you please remove the webcam feature for now?

**Comment by heysagnik** [comment]
Ohhh I understood the bug why it was not working when mic and webcam removed ,Normal people will face difficulty in that So 
It should run a check to find if the user has mic and webcam , if not present then the options will get disabled 

image

**Comment by thecodermaniac** [comment]
i will work on the issue assign me

**Comment by thecodermaniac** [comment]
https://github.com/heysagnik/screenREC/pull/54  pls merge the PR

**Comment by Suraj-Bhandarkar-S** [comment]
Hey @heysagnik can you add my name to contributors list :) it would mean a lot for my contribution!!

**Comment by heysagnik** [comment]
> oh okay I can add that check, do I still have to remove camera code?

When will you be able to finish this @Suraj-Bhandarkar-S ? 
So I can merge this soon 🚀.

**Comment by Suraj-Bhandarkar-S** [comment]
@heysagnik will add the check by today

**Pull request closed without merging**
