### PR TITLE
glassmorphism added to buttons and video preview

### PR DESCRIPTION
**Pull request by thecodermaniac**
image
record button 

image

video control buttons 

image

download buttons and  toggle button

### CODE REVIEW

**Comment by thecodermaniac** [comment]
pls merge @heysagnik

**Comment by thecodermaniac** [comment]
any change needed before merging? @heysagnik

**Comment by heysagnik** [comment]
Just Please improve the circles in Glassmorphism  Light mode

**Comment by thecodermaniac** [comment]
> Just Please improve the circles in Glassmorphism Light mode

the light background is custom made in accordance to real 
i did it in photoshop  will try once again but the result doesnt change much

**Review by thecodermaniac — COMMENTED** [review]
changes

**Pull request merged**
