### PR TITLE
added original figma created img

### PR DESCRIPTION
**Pull request by Sakshy18**
if figma links are needed contact me

### CODE REVIEW

**Comment by heysagnik** [comment]
I didn't asked for these 🤦 
Just a OG image like the one 
https://linear.app
OG

**Comment by Sakshy18** [comment]
I am not understanding,what exactly do u want me to make?

**Comment by heysagnik** [comment]
Send me a hi on my Discord `heysagnik#0692`

**Comment by heysagnik** [comment]
Sorry

**Pull request closed without merging**
